# Generated by Django 5.2.6 on 2025-09-26 19:44

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.CharField(help_text='MinIO object path', max_length=500, unique=True)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME type', max_length=100)),
                ('file_hash', models.CharField(help_text='SHA-256 hash for deduplication and integrity', max_length=64, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether the document is publicly accessible')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times this document has been downloaded')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='When the document was last accessed', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Document owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-modified'],
                'permissions': [('view_doc', 'Can view document'), ('edit_doc', 'Can edit document'), ('delete_doc', 'Can delete document'), ('download_doc', 'Can download document'), ('share_doc', 'Can share document')],
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', model_utils.fields.StatusField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('upload', 'Uploaded'), ('edit', 'Edited'), ('delete', 'Deleted'), ('share', 'Shared'), ('unshare', 'Unshared'), ('restore', 'Restored')], default='view', help_text='Action performed on the document', max_length=100, no_check_for_status=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional information about the access')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('permission_level', model_utils.fields.StatusField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('download', 'Can Download')], default='view', help_text='Permission level for the shared user', max_length=100, no_check_for_status=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the share expires (optional)', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times the shared user accessed the document')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='When the shared user last accessed the document', null=True)),
                ('permission_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='permission_level')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('shared_by', models.ForeignKey(help_text='User who shared the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_shared_by_me', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(help_text='User the document is shared with', on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-created'], name='documents_d_owner_i_152fca_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_d_file_ha_a7f76e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type'], name='documents_d_content_c2d034_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-modified'], name='documents_d_modifie_0d35c0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['document', '-created'], name='documents_a_documen_878281_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['user', '-created'], name='documents_a_user_id_349e22_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['action', '-created'], name='documents_a_action_6ae887_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['success', '-created'], name='documents_a_success_64a5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['shared_with', '-created'], name='documents_s_shared__3acb74_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['document', 'permission_level'], name='documents_s_documen_0e156e_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['expires_at'], name='documents_s_expires_c0d79d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('document', 'shared_with')},
        ),
    ]
