# Generated by Django 5.2.6 on 2025-09-27 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='documents.document')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Document Group Permission',
                'verbose_name_plural': 'Document Group Permissions',
                'indexes': [models.Index(fields=['group', 'permission'], name='documents_d_group_i_ccc645_idx'), models.Index(fields=['content_object', 'permission'], name='documents_d_content_2490e3_idx'), models.Index(fields=['group', 'content_object', 'permission'], name='documents_d_group_i_fa68ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='documents.document')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document User Permission',
                'verbose_name_plural': 'Document User Permissions',
                'indexes': [models.Index(fields=['user', 'permission'], name='documents_d_user_id_35cb5a_idx'), models.Index(fields=['content_object', 'permission'], name='documents_d_content_970c5d_idx'), models.Index(fields=['user', 'content_object', 'permission'], name='documents_d_user_id_416883_idx')],
            },
        ),
    ]
