# Generated by Django 5.2.6 on 2025-09-28 09:29

import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentgroupobjectpermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_error_message',
            field=models.TextField(blank=True, help_text='Error message if upload failed'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Upload progress information and metadata'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_status',
            field=model_utils.fields.StatusField(choices=[('pending', 'Upload Pending'), ('processing', 'Processing Upload'), ('completed', 'Upload Completed'), ('failed', 'Upload Failed')], default='completed', help_text='Current status of file upload processing', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async upload processing', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_status', '-created'], name='documents_d_upload__39533b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_task_id'], name='documents_d_upload__db2edf_idx'),
        ),
    ]
